# Generated by Django 4.2.23 on 2025-06-26 00:40

from django.db import migrations, models
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', null=True, upload_to='site_setup/favicon/%Y/%m/', validators=[utils.model_validators.validate_png]),
        ),
    ]
